django/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name="MovieList"),
    path('movies/top', views.TopMovies.as_view(), name='TopMovies'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name="MovieDetail"),
    path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name="CreateVote"),
    path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name='UpdateVote'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUpload.as_view(),
         name="MovieImageUpload"),
    path('person/<int:pk>', views.PersonDetail.as_view(), name='PersonDetail')
]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
    >
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <title>
        {% block title %}MyMDB{% endblock %}
    </title>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">MyMDB</div>
            <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
            <a class="nav-link"
               href="{% url 'core:TopMovies' %}">
                Top 10 Movies
            </a>
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'user:logout' %}">
                Log out
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'user:login' %}">
                Log in
            </a>
            <a class="nav-link" href="{% url 'user:register' %}">
                Register
            </a>
            {% endif %}
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>